# yaml-language-server: $schema=https://raw.githubusercontent.com/deepmap/oapi-codegen/HEAD/configuration-schema.json
package: api
generate:
  chi-server: true
  strict-server: true
  models: true
  embedded-spec: true
output: server.gen.go