openapi: 3.0.3
info:
  description: Campaign Manager Rest API.
  title: Campaign Manager
  version: 0.1.0
paths:
  /ping:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: OK
