// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts,import_extension=none"
// @generated from file proto/cm/v1/cm.proto (package proto.cm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { NewProjectRequest, NewProjectResponse, PingRequest, PingResponse } from "./cm_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.cm.v1.PingService
 */
export const PingService = {
  typeName: "proto.cm.v1.PingService",
  methods: {
    /**
     * @generated from rpc proto.cm.v1.PingService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

/**
 * @generated from service proto.cm.v1.NewProjectService
 */
export const NewProjectService = {
  typeName: "proto.cm.v1.NewProjectService",
  methods: {
    /**
     * @generated from rpc proto.cm.v1.NewProjectService.NewProject
     */
    newProject: {
      name: "NewProject",
      I: NewProjectRequest,
      O: NewProjectResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

