basePath: /api/v1
info:
  contact:
    email: pascal.post@mailbox.org
    name: Pascal Post
    url: https://github.com/pascalPost/campaign-manager
  description: Computation Campaign Manager REST API documentation.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Campaign Manager API
  version: "0.1"
paths:
  /test:
    get:
      description: GetTest returns OK
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: can be used to test the connection
swagger: "2.0"
