// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file proto/cm/v1/cm.proto (package proto.cm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { NewProjectRequest, NewProjectResponse } from "./cm_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service proto.cm.v1.NewProjectService
 */
export const NewProjectService = {
  typeName: "proto.cm.v1.NewProjectService",
  methods: {
    /**
     * @generated from rpc proto.cm.v1.NewProjectService.NewProject
     */
    newProject: {
      name: "NewProject",
      I: NewProjectRequest,
      O: NewProjectResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

