openapi: 3.0.3
info:
  title: Campaign Manager
  description: Campaign Manager Rest API.
  version: 0.1.0

paths:
  /ping:
    get:
      summary: Ping server
      responses:
        200:
          description: Success response
  /tasks:
    get:
      summary: List tasks
      responses:
        {}
    post:
      summary: Add new task
      responses:
        {}
  /projects:
    get:
      summary: List projects
      responses:
        {}
    post:
      summary: Add new projects
      responses:
        {}
  /files:
    get:
      summary: List files including folders
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - path
              properties:
                path:
                  type: string
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/File'
    post:
      summary: Add new file or folder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/File'
      responses:
        204:
          description: Success with no content
    delete:
      summary: Delete files or folders
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - path
              properties:
                path:
                  type: string
      responses:
        204:
          description: Success with no content
        404:
          description: Non-existing path
    put:
      summary: Update files
      responses:
        {}

components:
  schemas:
    File:
      required:
        - name
        - isDir
      properties:
        name:
          type: string
        isDir:
          type: boolean