# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json

openapi: 3.0.3
info:
  title: Campaign Manager
  description: Campaign Manager Rest API.
  version: 0.1.0

#servers:
#  - url: http://localhost:3000
#    description: Local Dev server

paths:
  /ping:
    get:
      summary: Ping server
      responses:
        200:
          description: Success response
  /jobs:
    get:
      summary: List jobs
      responses:
        { }
    post:
      summary: Add new job
      responses: { }
  /projects:
    get:
      summary: List projects
      responses: { }
    post:
      summary: Add new projects
      responses: { }