# yaml-language-server: $schema=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json

openapi: 3.0.3
info:
  title: Campaign Manager
  description: Campaign Manager Rest API.
  version: 0.1.0

#servers:
#  - url: http://localhost:3000
#    description: Local Dev server

paths:
  /ping:
    get:
      summary: Ping server
      responses:
        200:
          description: Success response
  /jobs:
    get:
      summary: List jobs
      responses:
        { }
    post:
      summary: Add new job
      responses: { }
  /projects:
    get:
      summary: List projects
      responses:
        200:
          description: Success response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Project'

    post:
      summary: Add new project
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                required:
                  - id
components:
  schemas:
    Project:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        path:
          type: string
      required:
        - id
        - name
        - path